# Generated by Django 5.1.6 on 2025-02-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(default='Medium', max_length=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
